//
//  topTipsStruct.swift
//  gymStart
//
//  Created by Jahangeer Aslam on 13/03/2021.
//

import Foundation
import UIKit

struct Data{ // all prederfined data needed
    
    //data required for the dashboardViewController
    struct homeTab{
        // data required for the personal Best section
        struct pbTile {
            static let pbExerciseNames = [
            "Bench Press",
            "Squats",
            "Deadlift"
            ]
        }
        // data required for the Top Tips section
        struct topTipsTile{
            static let gainMuscleData = [
                "Follow a high protien diet! You should be eating 1g of protien per pound of bodyweight",
                "Eating a meal as soon as you can after a workout can help your muscle recover sooner!",
                "In order to tone your muscles try perfroming your exercises with low weight and high reps!"
            ]
            static let looseFatData = [
                "Avoid drinking too much alcohol as it is usually high in calories!",
                "Eating more fiber every day can help boost your metbolsim!",
                "Cutting back on sugary drinks and refined carbs can help you lose subbon belly fat!"
            ]
            static let improveOverallHealthData = [
                "Exercising even 30 mins a day is proven to boost your mental health!",
                "Make sure to drink at least 2 liters of water every day!",
                "Getting enough sleep is imporant! Make sure your getting your 8 hours!"
            ]
            static let otherData = [
                "Make sure you are getting enough vitamin C every day. Its important for your health and can leave you feeling more energetic.",
                "Avoid processed foods! It only takes 15 mins to make a simple healthy meal",
                " Never underestimate the power of a good routine. It can help you stay on track to hit your goals and achieve your maximum potential"
            ]
        }
        
    }
    
    
    struct educateTab{
        
        static var exerciseGroups : [cellStruct] = [
            cellStruct( body: "Chest",image: "chestGroup.jpg"),
            cellStruct( body: "Arms",image: "armsGroup.jpg"),
            cellStruct( body: "Legs",image: "legsGroup.jpg"),
            cellStruct( body: "Back",image: "backGroup.jpg"),
            cellStruct( body: "Shoulders",image: "shouldersGroup.jpg")
            
            
        ]
        
        static var exerciseNames : [String : [String]] = [
            "Chest" : ["Bench Press", "Decline Bench Press", "Incline Bench Press", "PushUps"],
            "Arms" : ["Barbell Bicep Curl", "Skull Crushers", "Overhead Dumbell Press", "EZ barbell Curl", "Rear Dealt Flys"],
            "Legs" : ["Squats", "Barbell Squats", "Barbell Lunges", "Dumbell Squats"],
            "Back" : ["Deadlift", "Barbell Rows", "PullUps", "Single Arm Rows"],
            "Shoulders" : ["Front Plate Raise","Lat Raises", "Seated Shoulder Press", "Overhead Shoulder Press"]
            ]
        
        // information for all these exercises is taken from ACEfitness.org and MensHealth.com as well as addding peices from my own knowlegde into the instructions.
        static var listOfAllExercises : [exercisesStruct] = [
            //   "Chest" : ["Bench Press", "Decline Bench Press", "Incline Bench Press", "PushUps"],
            exercisesStruct( exerciseName: exerciseNames["Chest"]![0], exerciseImages: ["IMG_0982.jpg","IMG_0984.jpg", "IMG_0985.jpg", "IMG_0987.jpg"], exerciseInstructions: "\n Step 1 \n Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width.\n Step 2 \n Press the feet into the ground and the hips into the bench while lifting the bar off the rack. \n Step 3 \n Slowly lower the bar to the chest by allowing the elbows to bend out to the side. \n Step 4 \n Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position."),
            exercisesStruct( exerciseName: exerciseNames["Chest"]![1], exerciseImages: ["IMG_0995.jpg","IMG_0996.jpg", "IMG_0998.jpg", "IMG_0999.jpg"], exerciseInstructions: "\n Step 1 \n Grip the bar with your palms facing forward, arms slightly wider than shoulder-width apart. \n Step 2 \n Straighten your arms to lift the barbell from the rack. \n Step 3 \n Move it over your shoulders, locking your elbows. Inhale and slowly lower the barbell until it touches your mid-chest, keeping your elbows 45 degrees from your body/"),
            exercisesStruct( exerciseName: exerciseNames["Chest"]![2], exerciseImages: ["IMG_0988.jpg","IMG_0989.jpg", "IMG_0991.jpg", "IMG_0993.jpg"], exerciseInstructions: "Step 1 \n Starting Position: Grasp two dumbbells and lie supine (on your back) on an incline bench angled between 45 and 60 degrees with your feet placed firmly on the floor or on a raised platform to allow you to maintain a neutral spine (flat to normal curvature). \n Step 2 \n Depress and retract your scapulae (pull shoulders down and back) to make firm contact with the bench. Your head, shoulders, butt and feet should make contact with the bench and floor/riser throughout the exercise. If using a spotter, signal for assistance in moving to your starting position. Grasp each dumbbell with a closed, pronated grip (palms facing forward, thumbs wrapped around the handle) and press the dumbbells in unison to a level over your eyes or slightly higher, with your elbows fully extended. Maintain a neutral wrist position (avoid flexion / extension at the wrist joint).  \n Step 3 \n Downward Phase: Inhale and slowly lower the dumbbells in unison and in a controlled movement towards your upper chest, but moving slightly wider towards the armpits. Gently touch the dumbbells to your chest without bouncing, maintaining your neutral wrist position. Keep the elbows under your wrists, and either close to your sides (emphasizes more triceps) or flared out from the body (emphasizes more pectorals). Maintain all points of contact with the bench and floor/riser and avoid any arching in the low back. \n Step 4 \n Upward Phase: Exhale and gently press upwards to full elbow extension with the dumbbells positioned at your starting position. Maintain your points of contact with the bench and floor/riser, avoid arching your back during the lift and maintain your neutral wrist position throughout the movement. \n Step 5 \n At the end of the set, signal your spotter to assist you in taking the dumbbells and maintain a firm grip until the dumbbells are taken from your hands. \n Safety is very important in this exercise. A spotter should adopt a split-stance position with the hands positioned as close to the most distal (wrist) joint. Keep the hands near, but not touching the wrists unless needed."),
            exercisesStruct( exerciseName: exerciseNames["Chest"]![3], exerciseImages: ["IMG_1002.jpg","IMG_1003.jpg", "IMG_1004.jpg"], exerciseInstructions: " Step 1 \n Starting Position: Kneel on an exercise mat or floor and bring your feet together behind you. \n Step 2 \n Slowly bend forward to place your palms flat on the mat, positioning your hands shoulder-width apart with your fingers facing forward or turned slightly inward. Slowly shift your weight forward until your shoulders are positioned directly over your hands. Reposition your hands as needed to allow full extension of your body without any bend at the hips or knees. Stiffen your torso by contracting your core/abdominal muscles ('bracing'), your glute and quadriceps muscles and align your head with your spine. Place your feet together with your ankles dorsiflexed (toes pointed towards your shins). \n Step 3 \n Downward Phase: Slowly lower your body towards the floor while maintaining a rigid torso and head aligned with your spine. Do not allow your low back to sag or your hips to hike upwards during this downward phase. Continue to lower yourself until your chest or chin touch the mat/floor. Allow your elbows to flare outwards during the lowering phase. \n Step 4 \n Upward Phase: Press upwards through your arms while maintaining a rigid torso and head aligned with your spine. For extra strength think about pushing the floor away from you. Do not allow your low back to sag or your hips to hike upwards. Continue pressing until the arms are fully extended at the elbows.\n Step 5 \n An alternative position is to turn your hands to face forwards and keep your your elbows close to your sides during the downward phase. This shifts the emphasis from the chest muscles onto the triceps and may reduce stresses in the shoulder joint. Pushing through the heel and outside surface of your palm provides greater force in your press and stability to your shoulders."),

          //           "Arms" : ["Barbell Bicep Curl", "Skull Crushers", "Overhead Dumbell Press", "EZ barbell Curl", "Rear Dealt Flys"],
            exercisesStruct( exerciseName: exerciseNames["Arms"]![0], exerciseImages: ["IMG_1021.jpg","IMG_1022.jpg", "IMG_1023.jpg"], exerciseInstructions: "\n Step 1 \n Hold the barbell with both hands facing up so the wrists, elbows, and shoulders are in a straight line about shoulder-width apart. \n Step 2 \n Lift the barbell toward the shoulders while bending the elbows and keeping them next to the middle of the body.\n Step 3 \n Slowly lower the weight to return to the starting position. \n Step 4 \n Keep chest still, using just the arms for the movement."),
            exercisesStruct( exerciseName: exerciseNames["Arms"]![1], exerciseImages: ["IMG_1030.jpg","IMG_1031.jpg", "IMG_1032.jpg", "IMG_1033.jpg"], exerciseInstructions:"\n Step 1 \n Start standing with your feet shoulder width apart and dumbbells held in front of you. \n Step 2 \n Raise the dumbbells above your head until your arms are stretched out straight. \n Step 3 \n Slowly lower the weights back behind your head, being careful not to flare your elbows out too much. Once your forearms move beyond parallel to the floor bring the weight back up to the starting position. \n Step 4 \n Your upper arms should remain in place throughout the movement. Aim for four sets of eight to 12 reps." ),
            exercisesStruct( exerciseName: exerciseNames["Arms"]![2], exerciseImages:  ["IMG_1018.jpg","IMG_1058.jpg", "IMG_1059.jpg"],  exerciseInstructions: "\nStep 1\n Starting Position: Holding a barbell with a closed, pronated grip (palms facing your feet and thumbs wrapped around the bar), lie supine (on your back) on a flat bench with your feet firmly placed on the floor. Slowly press the barbell off your chest, fully extending your elbows until the barbell is positioned directly above your face with your palms still facing towards your feet. Maintain a neutral wrist position (no flexion or extension at the wrist). \nStep 2\n Downward Phase: Inhale and slowly bend the elbows, lowering the bar in a controlled manner towards your forehead or slightly behind your head while maintaining your neutral wrist position. Your upper arms should remain vertical to the floor as the elbows bend. Lower the bar until it sits just above your forehead or until you notice the upper arms begin to drift backwards. \nStep 3\n Upward Phase: Exhale and slowly return to your starting position with your elbows fully extended. Attempt to keep your upper arms vertical to the floor throughout the exercise and keep your elbows shoulder-width apart."),
            exercisesStruct( exerciseName: exerciseNames["Arms"]![3], exerciseImages: ["IMG_1047.jpg","IMG_1045.jpg", "IMG_1046.jpg"], exerciseInstructions: "\n Step 1 \n Hold the EZ bar with both hands facing up so the wrists, elbows, and shoulders are in a straight line about shoulder-width apart.\n Step 2 \n Postion your hands just arouns the indents of where the bar curls. Lift the EZ Bar toward the shoulders while bending the elbows and keeping them next to the middle of the body. \n Step 3 \n Slowly lower the weight to return to the starting position. Keep chest still, using just the arms for the movement."),
            exercisesStruct( exerciseName: exerciseNames["Arms"]![4], exerciseImages: ["IMG_1062.jpg","IMG_1063.jpg", "IMG_1065.jpg"], exerciseInstructions: "\n Step 1 \n   Assume a standing position with your feet shoulder width apart. \n Step 2 \n Hinge at the waist until your back is nearly parallel to the floor. \n Step 3 \n With your arms slightly bent, contract your rear deltoids to bring the weight up and out to your sides."),
            
        //    "Legs" : ["Squats", "Barbell Squats", "Barbell Lunges", "Dumbell Squats"],
            exercisesStruct( exerciseName: exerciseNames["Legs"]![0], exerciseImages: ["IMG_1015.jpg","IMG_1016.jpg", "IMG_1017.jpg"], exerciseInstructions: "\nStep 1\n Starting Position: Begin standing with your feet slightly wider than hip-width, with the toes turned slightly outwards with your hands by your sides so the palms facing inwards. Depress and retract your scapulae (pull the shoulders down and back). \nStep 2\n Stiffen your core and abdominal muscles (“bracing”) to stabilize your spine. Hold your chest up and out, tilt your head slightly up, shift your weight back into your heels while pushing your hips towards the wall behind you. \nStep 3\n Downward Phase: Start the downward phase by first shifting your hips backwards then downwards to create a hinge-like movement at your hips and knees simultaneously. As you lower your hips the knees will then start to shift forward slowly, but try to control the amount of forward translation (movement) of the tibia (shinbone). Maintain tension in the core muscles (continue bracing) and attempt to keep your back flat. \nStep 4\n Continue to lower yourself until your thighs are parallel or almost parallel with the floor, until your heels begin to lift off the floor, or until your torso begins to round or flex forward. Monitor your feet, ankles and knees, ensuring that the feet don't move, the ankles do not collapse in or out and the knees remain aligned over the second toe. \nStep 5\n From the Lowered Position: the knees should continue to remain aligned over the second toe and body weight should be evenly distributed between the balls and heels of the feet. From the side, the position of the tibia (shinbone) and torso should be parallel with each other and the low back should appear flat or showing the beginning of some rounding. \nStep 6\n Upward Phase: While maintaining your back, chest and head-up position, exhale and extend the hips and knees by pushing your feet into the floor through your heels. The hips and torso need to rise together while keeping the heels flat on the floor and knees aligned over the second toe. Continue extending until you reach your starting position. \n Think about inhaling on the way down and exhaling while exerting on the way back to the initial standing position. "),
            exercisesStruct( exerciseName: exerciseNames["Legs"]![1], exerciseImages: ["IMG_1018.jpg","IMG_1019.jpg", "IMG_1020.jpg"], exerciseInstructions: "\n Step 1 \nTo perform the back squat, grab a barbell inside a squat rack with your hands a bit wider than shoulder-width apart. \n Step 2 \nFrom there, duck underneath the bar and push your upper back against the bar, so that the bar is resting on the very top of your upper back. \n Step 3 \nSqueeze your shoulder blades together to create a muscular “shelf” for the bar to rest on. Stand up tall and walk yourself backwards, a few steps away from the squat rack.\n Step 4 \n Place your feet slightly wider than shoulder-width apart and turn your feet out a little, 20 to 30 degrees. Then, push your hips back and bend your knees to lower into a squat, pushing your knees slightly out to the sides. k. \n Step 5 \n Only squat as deeply as your mobility allows.Push through both feet to stand back up"),
            exercisesStruct( exerciseName: exerciseNames["Legs"]![2], exerciseImages: ["IMG_1026.jpg","IMG_1027.jpg", "IMG_1028.jpg", "IMG_1029.jpg"], exerciseInstructions: "\n Step 1 \n Place a barbell in a rack at approximately shoulder-height. Dip under the bar so that it rests behind the neck across the top of the back and shoulder blades, and grip the bar with the hands a little wider than shoulder-width apart. \n Step 2 \n Lift the chest and squeeze the shoulder blades together to keep the back straight through the entire movement. Stand up to bring the bar off the rack and take 2 steps backwards. \n Step 3 \n Place both feet so that they are about hip-width apart, and step forward with the right leg. Lower the left knee almost to the floor without touching the ground. \n Step 4 \n From the bottom of the movement push the right foot into the floor and pull back with the left leg to stand up. \n Step 5 \nAlternate the legs for the desired number of repetitions."),
            exercisesStruct( exerciseName: exerciseNames["Legs"]![3], exerciseImages: ["IMG_1057.jpg","IMG_1058.jpg", "IMG_1059.jpg"], exerciseInstructions: "\n Step 1 \n Stand with the feet about shoulder-width apart, and hold a dumbbell in a vertical position directly in front of the chest. \n Step 2 \n Keep the elbows close to the rib cage and the back straight while lowering into a squat. \n Step 3 \n Continue lowering until the hips are below the knees, then push both feet into the floor and to return back to the original standing position."),
        
         //   "Back" : ["Deadlift", "Barbell Rows", "PullUps", "Single Arm Rows"],
            exercisesStruct( exerciseName: exerciseNames["Back"]![0], exerciseImages: ["IMG_1005.jpg","IMG_1006.jpg", "IMG_1007.jpg"], exerciseInstructions: "\n Step 1 \n Holding a barbell with both hands so that it rests on the front of the thighs, keep a slight bend in both knees and a straight back. \n Step 2 \n Push the hips back while lowering the weight towards the floor until feeling some tension along the back of the legs. \n Step 3 \n To return to standing, push the heels into the floor and pull the knees backwards, keeping the bar very close to the body while standing."),
            exercisesStruct( exerciseName: exerciseNames["Back"]![1], exerciseImages: ["IMG_1008.jpg","IMG_1009.jpg", "IMG_1010.jpg"], exerciseInstructions: " \n Step 1 \n Starting Position: Holding a dumbbell in your right hand, bend over to place your left knee and left hand on a bench to support your body weight. Your hand should be placed directly under your shoulder and your knees should be positioned directly under your hips. Gently contract your abdominal / core muscles ('bracing') to stiffen your torso and stabilize your spine. Your back should be flat and head aligned with your spine. Depress and retract your scapulae (pull your shoulders down and back) without arching your low back and maintain this shoulder position throughout the exercise. Extend your right arm (holding the dumbbell) towards the floor without allowing your torso to rotate or shoulder to move towards the floor. \n Step 2 \n Upward Movement: Exhale and slowly pull the dumbbell upwards, bending your elbow and pulling your upper arm backwards. Keep your arm close to the side of your body and continue pulling the dumbbell upwards until you are unable to lift any further without rotating your torso. Avoid rotating your body or changing the position of your spine throughout the lift. \n Step 3 \n Downward Movement: Inhale and gently lower the dumbbell to your starting position while maintaining a flat back and retracted (pulled back) shoulder position. Try performing this exercise alongside a mirror to monitor any change in your back or shoulder position and check for trunk rotation. "),
            exercisesStruct( exerciseName: exerciseNames["Back"]![2], exerciseImages: ["IMG_1012.jpg","IMG_1013.jpg", "IMG_1014.jpg"], exerciseInstructions: "\n Step 1 \n Starting Position: Stand under the chin-up bar and reach your arms overhead with your palms facing away from you. Reach, jump or lift your body off the floor to grasp the handles firmly with a full grip position (thumbs wrapped around the handles). Gently cross one leg over the other to stabilize your lower extremity and then stiffen ('brace') your abdominal muscles to stabilize your spine. Align your head vertically with your trunk under your hands and assume a neutral wrist position (i.e., wrist aligned in a straight line with your forearms). Depress and retract your scapulae (pull shoulders back and down) and attempt to hold this position throughout the exercise. \nStep 2\n Slowly exhale and slowly pull your body upwards by flexing (bending) your elbows and pulling your elboes down to your sides Attempt to pull in a motion that drives your elbows directly down towards the floor, while keeping them positioned in the 3 and 9 o'clock position (aligned with the sides of the trunk). Attempt to keep your body aligned vertically to the floor and avoid swinging your body during your upward pull \nStep 3\n Continue pulling upward until your chin is level with the bar or your hands. Pause momentarily then slowly return to your starting position by allowing your arms to extend back overhead until your arms are fully extended. Continue to maintain your shoulder and wrist position, and the vertical alignment of your trunk. Repeat the movement. \nStep 4\n Exercise Variation: The intensity of this exercise can be increased with resistance that can be added by wearing a weight belt to which weights are connected. Using a narrow, prontated (palms forward) grip shifts some of the load from your lats (mid-back muscles) into the muscles of the upper back. This exercise targets the back muscles effectively, but should be performed without compromise to the shoulder. Follow the instructions provided to reduce the stress placed upon your shoulders "),
            exercisesStruct( exerciseName: exerciseNames["Back"]![3], exerciseImages: ["IMG_1072.jpg","IMG_1073.jpg", "IMG_1075.jpg"], exerciseInstructions: "\n Step 1 \n Starting Position: Holding a dumbbell in your right hand, bend over to place your left knee and left hand on a bench to support your body weight. Your hand should be placed directly under your shoulder and your knees should be positioned directly under your hips. Gently contract your abdominal / core muscles to stiffen your torso and stabilize your spine. Your back should be flat and head aligned with your spine. Depress and retract your scapulae (pull your shoulders down and back) without arching your low back and maintain this shoulder position throughout the exercise. Extend your right arm (holding the dumbbell) towards the floor without allowing your torso to rotate or shoulder to move towards the floor.\n Step 2 \n Upward Movement: Exhale and slowly pull the dumbbell upwards, bending your elbow and pulling your upper arm backwards. Keep your arm close to the side of your body and continue pulling the dumbbell upwards until you are unable to lift any further without rotating your torso. Avoid rotating your body or changing the position of your spine throughout the lift.\n Step 3 \n Downward Movement: Inhale and gently lower the dumbbell to your starting position while maintaining a flat back and retracted (pulled back) shoulder position."),
        
            
          //  "Shoulders" : ["Front Plate Raise","Lat Raises", "Seated Shoulder Press", "Overhead Shoulder Press"]
            exercisesStruct( exerciseName: exerciseNames["Shoulders"]![0], exerciseImages:["IMG_1034.jpg","IMG_1035.jpg", "IMG_1036.jpg"], exerciseInstructions: "\nStep 1\n  Stand upright and grip a weight plate with your hands at the 3 o'clock and 9 o'clock positions respectively. \nStep 2\n For the start position hold the weight by your waist. \nStep 3 \n Slowly raise the plate past shoulder level while keeping your arms extended. Lower and repeat."),
            exercisesStruct( exerciseName: exerciseNames["Shoulders"]![1], exerciseImages:["IMG_1049.jpg","IMG_1050.jpg", "IMG_1051.jpg"], exerciseInstructions: "\nStep 1\n Starting Position: Stand holding dumbbells or small weight plates in your hands with a closed, neutral grip (thumbs around the handles and palms facing your body). Position the dumbbells alongside your thighs with your elbows extended or holding a slight bend. Assume either a split-stance position to stabilize your body or position your feet slightly wider than hip-width apart. \nStep 2\n Stiffen your torso by contracting your abdominal and core muscles ('bracing'), and depress and retract your scapulae (pull your shoulders down and back), maintaining this position throughout the exercise. Your head position should be aligned with your spine. \nStep 3\n Upward Phase: Exhale and slowly raise the dumbbells up and out to your sides. Your elbows and upper arms should rise together and be slightly ahead of your forearms and weights. As your arms move past 60 - 70 degrees (nearing shoulder level), rotate them slightly upwards so that the front edge of the dumbbells point slightly upwards. Continue raising the dumbbells until your arms are level with your shoulders and approximately parallel with the floor. Maintain your torso erect (no arching your low back) and neutral wrist position (avoid flexion and extension of your wrists). \nStep 4\n Downward Phase: Inhale and gently lower the weights back towards your starting position keeping your elbows slightly extended and holding the neutral grip position. Maintain your foot, torso, shoulder and wrist positions while lowering the dumbbells and rotating them slightly downwards as your arms pass that 60-70 degree mark. As this exercise traditionally positions the arms into internal rotation during the lift, the slight external rotation initiated at the 60-70 degree mark may reduce potential impingement in the shoulder joint."),
            exercisesStruct( exerciseName: exerciseNames["Shoulders"]![2], exerciseImages:["IMG_1067.jpg","IMG_1069.jpg", "IMG_1070.jpg", "IMG_1071.jpg"], exerciseInstructions: "\n Step 1 \n Sit in a shoulder-press bench and rack, and keep the back straight while gripping the bar with the hands a little wider than shoulder-width apart. \n Step 2 \n Take the bar out of the rack and slowly lower to the front of the shoulders, stopping when the bar is about chin-height. \n Step 3 \n Press the feet into the floor, squeeze the stomach muscles, and keep the elbows pointed forward while pressing the bar directly overhead.\n Step 4 \n Slowly lower the bar to chin-height and repeat for the desired number of repetitions."),
            exercisesStruct( exerciseName: exerciseNames["Shoulders"]![3], exerciseImages:["IMG_1077.jpg","IMG_1078.jpg", "IMG_1079.jpg"], exerciseInstructions: "\n Step 1 \n Place a barbell behind your neck at about a good height . Grip the bar with the hands about shoulder-width apart and the palm facing the ceiling. \n Step 2 \n Dip under the bar to bring it off the rack letting it rest across the top of the shoulders so that the palms are facing the ceiling and the elbows are pointed straight ahead. \n Step 3 \n Step back, keeping the back straight and tall and press the barbell directly overhead. \n Step 4 \n Slowly return the weight to the behind the neck and repeat for the desired number of reps."),
            
            
        ]
        
    }
    
    struct logsTab{
        static let setArray = ["SET 1", "SET 2", "SET 3","SET 4","SET 5"]
    }
     
        
        
        
        
    
}
    

    
    

